### ISSUE TITLE
Errors when working with the Batches page

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#125]
Lately, I am frequently getting errors when working with the batch page at https://tools.wmflabs.org/author-disambiguator/batches_oauth.php . Here is one from just a moment ago
```
Warning: mysqli::query(): Couldn't fetch mysqli in /data/project/author-disambiguator/public_html/lib/batch.php on line 79

Fatal error: Uncaught Error: Call to a member function fetch_row() on bool in /data/project/author-disambiguator/public_html/lib/batch.php:80 Stack trace: #0 /data/project/author-disambiguator/public_html/batches_oauth.php(81): Batch::batches_for_owner(Object(mysqli), 'Daniel Mietchen') #1 {main} thrown in /data/project/author-disambiguator/public_html/lib/batch.php on line 80
```

Here is another one from https://tools.wmflabs.org/author-disambiguator/batches_oauth.php?action=restart&batch_id=dc66fa :

```

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /data/project/author-disambiguator/public_html/lib/batch.php on line 23

Warning: mysqli::query(): Couldn't fetch mysqli in /data/project/author-disambiguator/public_html/lib/batch.php on line 25

Fatal error: Uncaught Error: Call to a member function fetch_row() on bool in /data/project/author-disambiguator/public_html/lib/batch.php:26 Stack trace: #0 /data/project/author-disambiguator/public_html/batches_oauth.php(36): Batch->load(Object(mysqli)) #1 {main} thrown in /data/project/author-disambiguator/public_html/lib/batch.php on line 26

```

There are often similar errors on the work or author pages, but so far, they have not inhibited the functionality I needed, so haven't reported them as yet.

**Comment by arthurpsmith** [comment]
Yup, I hadn't noticed this before today, I have no idea what's made this break, but it is a big problem!

**Comment by arthurpsmith** [comment]
I added a bit more error checking on the mysql stuff; hopefully if this happens again we'll get more of an explanation at least!
